[build]
  # Build command for Vite React project
  command = "npm run build"
  
  # Directory where build output is generated
  publish = "dist"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://*.google.com wss://*.firebaseio.com; frame-src https://accounts.google.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Production environment variables (set these in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

# Deploy preview environment
[context.deploy-preview.environment]
  NODE_ENV = "development"

# Branch deploy environment
[context.branch-deploy.environment]
  NODE_ENV = "development"